using System.Globalization;
using System.Net;
using System.Text;
using System.Text.Json;
using Npgsql;

namespace AutoMateApi;

public static class QuoteWorkflowSupport
{
    private static readonly JsonSerializerOptions JsonOptions=new(JsonSerializerDefaults.Web);
    public static async Task EnsureAsync(NpgsqlConnection connection,CancellationToken ct=default)
    {
        const string sql="""
CREATE TABLE IF NOT EXISTS public.tenant_quote_settings(tenant_id uuid PRIMARY KEY,default_validity_days integer NOT NULL DEFAULT 30,introduction_text text NOT NULL DEFAULT 'Thank you for the opportunity to quote for your property inspection.',updated_at timestamptz NOT NULL DEFAULT NOW(),CONSTRAINT ck_quote_validity CHECK(default_validity_days BETWEEN 1 AND 365));
CREATE TABLE IF NOT EXISTS public.quotes(quote_id uuid PRIMARY KEY,tenant_id uuid NOT NULL,quote_number text NOT NULL,status text NOT NULL,version integer NOT NULL,catalogue_version integer NOT NULL,canonical_address text NOT NULL,place_id text NOT NULL DEFAULT '',latitude double precision NULL,longitude double precision NULL,client_name text NOT NULL DEFAULT '',client_email text NOT NULL DEFAULT '',property_json jsonb NOT NULL DEFAULT '{}'::jsonb,imagery_json jsonb NOT NULL DEFAULT '{}'::jsonb,suggestions_json jsonb NOT NULL DEFAULT '[]'::jsonb,lines_json jsonb NOT NULL DEFAULT '[]'::jsonb,subtotal numeric(12,2) NOT NULL,gst numeric(12,2) NOT NULL,total numeric(12,2) NOT NULL,valid_until date NOT NULL,created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT NOW(),updated_at timestamptz NOT NULL DEFAULT NOW(),accepted_at timestamptz NULL,declined_at timestamptz NULL,converted_at timestamptz NULL,UNIQUE(tenant_id,quote_number),CONSTRAINT ck_quote_status CHECK(status IN ('Draft','Ready','Sent','Viewed','Accepted','Declined','Expired','Converted')));
CREATE INDEX IF NOT EXISTS idx_quotes_tenant_updated ON public.quotes(tenant_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS public.quote_versions(quote_id uuid NOT NULL,tenant_id uuid NOT NULL,version integer NOT NULL,snapshot_json jsonb NOT NULL,created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT NOW(),PRIMARY KEY(quote_id,version));
CREATE TABLE IF NOT EXISTS public.quote_commands(tenant_id uuid NOT NULL,idempotency_key text NOT NULL,quote_id uuid NOT NULL,result_json jsonb NULL,created_at timestamptz NOT NULL DEFAULT NOW(),PRIMARY KEY(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS public.quote_public_links(link_id uuid PRIMARY KEY,tenant_id uuid NOT NULL,quote_id uuid NOT NULL,quote_version integer NOT NULL,token_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,revoked_at timestamptz NULL,first_viewed_at timestamptz NULL,last_viewed_at timestamptz NULL,visit_count integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT NOW(),UNIQUE(quote_id,quote_version));
CREATE TABLE IF NOT EXISTS public.quote_decisions(decision_id uuid PRIMARY KEY,tenant_id uuid NOT NULL,quote_id uuid NOT NULL,quote_version integer NOT NULL,decision text NOT NULL,occurred_at timestamptz NOT NULL DEFAULT NOW(),ip_hash text NOT NULL DEFAULT '',UNIQUE(quote_id,quote_version),CONSTRAINT ck_quote_decision CHECK(decision IN ('Accepted','Declined')));
""";
        await using var command=new NpgsqlCommand(sql,connection);await command.ExecuteNonQueryAsync(ct);
    }

    public static async Task<object> CatalogueAsync(NpgsqlConnection connection,Guid tenantId,CancellationToken ct=default)
    {
        var active=await TenantServiceCatalogueSupport.LoadActiveAsync(connection,tenantId,ct);
        var categories=active.Draft.Categories.ToDictionary(x=>x.Id,x=>x.Name);
        var services=active.Draft.Services.Where(x=>!x.Archived).Select(x=>{
            var binding=x.Bindings.FirstOrDefault(b=>b.Active&&b.InvoiceItemPrice.HasValue);
            return new{serviceId=x.Id,name=x.Name,categoryId=x.CategoryId,categoryName=categories.GetValueOrDefault(x.CategoryId,"Service"),description=binding?.InvoiceItemName??x.Name,unitPrice=binding?.InvoiceItemPrice,gstRate=0.15m,active=binding!=null};
        }).Where(x=>x.active).ToList();
        var modifiers=active.Draft.ModifierGroups.Where(x=>!x.Archived).SelectMany(g=>g.Options.Where(o=>o.Active&&o.InvoiceItemPrice.HasValue).Select(o=>new{modifierId=$"{g.Id:D}:{o.ListItemId}",groupId=g.Id,groupName=g.Name,name=o.ListItemName,description=o.InvoiceItemName,unitPrice=o.InvoiceItemPrice,gstRate=0.15m,active=true})).ToList();
        var quantityPricingRules=(active.Draft.QuantityPricingRules??[]).Where(x=>x.Active).Select(x=>new{ruleId=x.Id,source=x.SourceCanonicalField,invoiceItemId=x.InvoiceItemId,description=x.InvoiceItemName,unitRateInclGst=x.UnitRateInclGst,allCategories=x.AllCategories,categoryIds=x.CategoryIds,active=x.Active}).ToList();
        return new{catalogueVersion=active.Version,services,modifiers,quantityPricingRules};
    }

    public static async Task<object> ListAsync(NpgsqlConnection connection,Guid tenantId,CancellationToken ct=default)
    {
        await EnsureAsync(connection,ct);await EnsureSettingsAsync(connection,tenantId,ct);
        var quotes=new List<object>();const string sql="SELECT quote_id,quote_number,status,version,canonical_address,client_name,total,valid_until,updated_at FROM public.quotes WHERE tenant_id=@tenant ORDER BY updated_at DESC LIMIT 250";
        await using(var command=new NpgsqlCommand(sql,connection)){command.Parameters.AddWithValue("tenant",tenantId);await using var reader=await command.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))quotes.Add(new{quoteId=reader.GetGuid(0),quoteNumber=reader.GetString(1),status=EffectiveStatus(reader.GetString(2),reader.GetDateTime(7)),version=reader.GetInt32(3),canonicalAddress=reader.GetString(4),clientName=reader.GetString(5),total=reader.GetDecimal(6),validUntil=reader.GetDateTime(7).ToString("yyyy-MM-dd"),updatedAt=reader.GetDateTime(8)});}
        await using var setting=new NpgsqlCommand("SELECT default_validity_days FROM public.tenant_quote_settings WHERE tenant_id=@tenant",connection);setting.Parameters.AddWithValue("tenant",tenantId);var days=Convert.ToInt32(await setting.ExecuteScalarAsync(ct));return new{quotes,defaultValidityDays=days};
    }

    public static async Task<object?> LoadAsync(NpgsqlConnection connection,Guid tenantId,Guid quoteId,CancellationToken ct=default)
    {
        await EnsureAsync(connection,ct);const string sql="SELECT quote_id,quote_number,status,version,catalogue_version,canonical_address,place_id,latitude,longitude,client_name,client_email,property_json::text,imagery_json::text,suggestions_json::text,lines_json::text,subtotal,gst,total,valid_until,created_at,updated_at,accepted_at,declined_at FROM public.quotes WHERE tenant_id=@tenant AND quote_id=@quote";
        await using var command=new NpgsqlCommand(sql,connection);command.Parameters.AddWithValue("tenant",tenantId);command.Parameters.AddWithValue("quote",quoteId);await using var reader=await command.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))return null;return Row(reader,true);
    }

    public static async Task<QuoteSaveResult> SaveAsync(NpgsqlConnection connection,QuoteDraftSaveRequest request,string actor,string pepper,CancellationToken ct=default)
    {
        if(!request.Confirmed)throw new InvalidOperationException("Confirm the quote draft save.");if(string.IsNullOrWhiteSpace(request.IdempotencyKey))throw new InvalidOperationException("An idempotency key is required.");
        await EnsureAsync(connection,ct);var active=await TenantServiceCatalogueSupport.LoadActiveAsync(connection,request.TenantId,ct);if(active.Version<1)throw new InvalidOperationException("Activate the THREED service catalogue before creating quotes.");
        var serviceMap=active.Draft.Services.Where(x=>!x.Archived).ToDictionary(x=>x.Id.ToString("D"),StringComparer.OrdinalIgnoreCase);
        var modifierMap=active.Draft.ModifierGroups.Where(x=>!x.Archived).SelectMany(group=>group.Options.Where(option=>option.Active&&option.InvoiceItemPrice.HasValue).Select(option=>new{Id=$"{group.Id:D}:{option.ListItemId}",Group=group,Option=option})).ToDictionary(x=>x.Id,StringComparer.OrdinalIgnoreCase);var lines=new List<QuoteStoredLine>();var selectedCategoryIds=new HashSet<Guid>();
        foreach(var selected in request.Draft.Lines.Where(x=>x.Confirmed))
        {
            var qty=selected.Quantity<=0?1:selected.Quantity;
            if(serviceMap.TryGetValue(selected.CatalogueItemId,out var service)){var binding=service.Bindings.FirstOrDefault(x=>x.Active&&x.InvoiceItemPrice.HasValue)??throw new InvalidOperationException($"{service.Name} has no active THREED invoice price.");var unit=Money(binding.InvoiceItemPrice!.Value);selectedCategoryIds.Add(service.CategoryId);lines.Add(new(selected.CatalogueItemId,service.Name,binding.InvoiceItemName,qty,unit,Money(qty*unit),selected.IsBaseItem,selected.Evidence??"Office selection",binding.InvoiceItemId));continue;}
            if(modifierMap.TryGetValue(selected.CatalogueItemId,out var modifier)){var unit=Money(modifier.Option.InvoiceItemPrice!.Value);lines.Add(new(selected.CatalogueItemId,modifier.Option.ListItemName,modifier.Option.InvoiceItemName,qty,unit,Money(qty*unit),false,selected.Evidence??"Office-confirmed property modifier",modifier.Option.InvoiceItemId));continue;}
            throw new InvalidOperationException("A selected Service or modifier is not in the active THREED catalogue.");
        }
        if(lines.Count(x=>x.IsBaseItem)!=1)throw new InvalidOperationException("Select exactly one primary THREED Service.");if(string.IsNullOrWhiteSpace(request.Draft.CanonicalAddress))throw new InvalidOperationException("Confirm the canonical property address.");
        foreach(var rule in (active.Draft.QuantityPricingRules??[]).Where(x=>x.Active&&(x.AllCategories||(x.CategoryIds??[]).Any(selectedCategoryIds.Contains))))
        {
            var area=ReadFloorArea(request.Draft.Property);if(!area.HasValue||area.Value<=0)throw new InvalidOperationException("Property floor area is required by the active per-m² pricing rule. Confirm the PropertyValue area or enter a verified manual area before Save or Send.");var unit=Money(rule.UnitRateInclGst);var areaLine=new QuoteStoredLine("quantity:"+rule.Id.ToString("D"),"Property floor area",rule.InvoiceItemName,area.Value,unit,Money(area.Value*unit),false,"Office-confirmed property floor area",rule.InvoiceItemId);var existing=lines.FindIndex(x=>!string.IsNullOrWhiteSpace(x.InvoiceItemId)&&string.Equals(x.InvoiceItemId,rule.InvoiceItemId,StringComparison.OrdinalIgnoreCase));if(existing>=0)lines[existing]=areaLine;else lines.Add(areaLine);
        }
        var total=Money(lines.Sum(x=>x.Amount));var gst=Money(total*3m/23m);var subtotal=Money(total-gst);var quoteId=request.QuoteId??Guid.NewGuid();var version=1;var status=request.Draft.Ready?"Ready":"Draft";var valid=request.Draft.ValidUntil?.Date??DateTime.UtcNow.Date.AddDays(30);
        await using var tx=await connection.BeginTransactionAsync(ct);
        await using(var replay=new NpgsqlCommand("SELECT result_json::text FROM public.quote_commands WHERE tenant_id=@tenant AND idempotency_key=@key",connection,tx)){replay.Parameters.AddWithValue("tenant",request.TenantId);replay.Parameters.AddWithValue("key",request.IdempotencyKey);var prior=await replay.ExecuteScalarAsync(ct) as string;if(!string.IsNullOrWhiteSpace(prior)){await tx.RollbackAsync(ct);var saved=JsonSerializer.Deserialize<QuoteSaveResult>(prior,JsonOptions)!;return saved with{PublicToken=null,Replayed=true};}}
        if(request.QuoteId.HasValue){await using var current=new NpgsqlCommand("SELECT version,status FROM public.quotes WHERE tenant_id=@tenant AND quote_id=@quote FOR UPDATE",connection,tx);current.Parameters.AddWithValue("tenant",request.TenantId);current.Parameters.AddWithValue("quote",quoteId);await using var rr=await current.ExecuteReaderAsync(ct);if(!await rr.ReadAsync(ct))throw new InvalidOperationException("Quote not found for this company.");var currentVersion=rr.GetInt32(0);var currentStatus=rr.GetString(1);await rr.DisposeAsync();if(currentVersion!=request.ExpectedVersion)throw new QuoteVersionConflictException();if(currentStatus is "Accepted" or "Declined" or "Converted")throw new InvalidOperationException("Decided quotes are immutable.");version=currentVersion+1;}
        var number=$"Q-{DateTime.UtcNow:yyyy}-{quoteId.ToString("N")[..6].ToUpperInvariant()}";var linesJson=JsonSerializer.Serialize(lines,JsonOptions);var propertyJson=JsonSerializer.Serialize(request.Draft.Property??new{},JsonOptions);var imageryJson=JsonSerializer.Serialize(request.Draft.Imagery??new{},JsonOptions);var suggestionsJson=JsonSerializer.Serialize(request.Draft.Suggestions??[],JsonOptions);
        const string upsert="""INSERT INTO public.quotes(quote_id,tenant_id,quote_number,status,version,catalogue_version,canonical_address,place_id,latitude,longitude,client_name,client_email,property_json,imagery_json,suggestions_json,lines_json,subtotal,gst,total,valid_until,created_by) VALUES(@id,@tenant,@number,@status,@version,@catalogue,@address,@place,@lat,@lng,@client,@email,@property::jsonb,@imagery::jsonb,@suggestions::jsonb,@lines::jsonb,@subtotal,@gst,@total,@valid,@actor) ON CONFLICT(quote_id) DO UPDATE SET status=EXCLUDED.status,version=EXCLUDED.version,catalogue_version=EXCLUDED.catalogue_version,canonical_address=EXCLUDED.canonical_address,place_id=EXCLUDED.place_id,latitude=EXCLUDED.latitude,longitude=EXCLUDED.longitude,client_name=EXCLUDED.client_name,client_email=EXCLUDED.client_email,property_json=EXCLUDED.property_json,imagery_json=EXCLUDED.imagery_json,suggestions_json=EXCLUDED.suggestions_json,lines_json=EXCLUDED.lines_json,subtotal=EXCLUDED.subtotal,gst=EXCLUDED.gst,total=EXCLUDED.total,valid_until=EXCLUDED.valid_until,updated_at=NOW()""";
        await using(var save=new NpgsqlCommand(upsert,connection,tx)){save.Parameters.AddWithValue("id",quoteId);save.Parameters.AddWithValue("tenant",request.TenantId);save.Parameters.AddWithValue("number",number);save.Parameters.AddWithValue("status",status);save.Parameters.AddWithValue("version",version);save.Parameters.AddWithValue("catalogue",active.Version);save.Parameters.AddWithValue("address",request.Draft.CanonicalAddress.Trim());save.Parameters.AddWithValue("place",request.Draft.PlaceId??"");save.Parameters.AddWithValue("lat",(object?)request.Draft.Latitude??DBNull.Value);save.Parameters.AddWithValue("lng",(object?)request.Draft.Longitude??DBNull.Value);save.Parameters.AddWithValue("client",request.Draft.ClientName?.Trim()??"");save.Parameters.AddWithValue("email",request.Draft.ClientEmail?.Trim().ToLowerInvariant()??"");save.Parameters.AddWithValue("property",propertyJson);save.Parameters.AddWithValue("imagery",imageryJson);save.Parameters.AddWithValue("suggestions",suggestionsJson);save.Parameters.AddWithValue("lines",linesJson);save.Parameters.AddWithValue("subtotal",subtotal);save.Parameters.AddWithValue("gst",gst);save.Parameters.AddWithValue("total",total);save.Parameters.AddWithValue("valid",valid);save.Parameters.AddWithValue("actor",actor);await save.ExecuteNonQueryAsync(ct);}
        var snapshot=JsonSerializer.Serialize(new{quoteId,number,status,version,catalogueVersion=active.Version,request.Draft.CanonicalAddress,request.Draft.ClientName,request.Draft.ClientEmail,lines,subtotal,gst,total,validUntil=valid.ToString("yyyy-MM-dd")},JsonOptions);await using(var history=new NpgsqlCommand("INSERT INTO public.quote_versions(quote_id,tenant_id,version,snapshot_json,created_by) VALUES(@id,@tenant,@version,@snapshot::jsonb,@actor)",connection,tx)){history.Parameters.AddWithValue("id",quoteId);history.Parameters.AddWithValue("tenant",request.TenantId);history.Parameters.AddWithValue("version",version);history.Parameters.AddWithValue("snapshot",snapshot);history.Parameters.AddWithValue("actor",actor);await history.ExecuteNonQueryAsync(ct);}
        string? publicToken=null;if(status=="Ready"&&!string.IsNullOrWhiteSpace(pepper)){var token=QuotePublicToken.Create("quote_details",pepper);publicToken=token.Secret;await using var link=new NpgsqlCommand("INSERT INTO public.quote_public_links(link_id,tenant_id,quote_id,quote_version,token_hash,expires_at) VALUES(@link,@tenant,@quote,@version,@hash,@expires) ON CONFLICT(quote_id,quote_version) DO NOTHING",connection,tx);link.Parameters.AddWithValue("link",Guid.NewGuid());link.Parameters.AddWithValue("tenant",request.TenantId);link.Parameters.AddWithValue("quote",quoteId);link.Parameters.AddWithValue("version",version);link.Parameters.AddWithValue("hash",token.TokenHash);link.Parameters.AddWithValue("expires",new DateTimeOffset(valid.AddDays(1),TimeSpan.Zero));await link.ExecuteNonQueryAsync(ct);}
        var result=new QuoteSaveResult(quoteId,number,status,version,active.Version,subtotal,gst,total,valid.ToString("yyyy-MM-dd"),publicToken,false);var replayRecord=result with{PublicToken=null};var resultJson=JsonSerializer.Serialize(replayRecord,JsonOptions);await using(var command=new NpgsqlCommand("INSERT INTO public.quote_commands(tenant_id,idempotency_key,quote_id,result_json) VALUES(@tenant,@key,@quote,@json::jsonb)",connection,tx)){command.Parameters.AddWithValue("tenant",request.TenantId);command.Parameters.AddWithValue("key",request.IdempotencyKey);command.Parameters.AddWithValue("quote",quoteId);command.Parameters.AddWithValue("json",resultJson);await command.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return result;
    }

    public static async Task<QuotePublicAccess?> ResolvePublicAsync(NpgsqlConnection connection,string token,string pepper,bool recordView,CancellationToken ct=default)
    {
        await EnsureAsync(connection,ct);var hash=QuotePublicToken.Hash(token,"quote_details",pepper);const string sql="SELECT l.link_id,l.tenant_id,l.quote_id,l.quote_version,l.expires_at,l.revoked_at,q.quote_number,q.status,q.canonical_address,q.client_name,q.lines_json::text,q.subtotal,q.gst,q.total,q.valid_until,q.accepted_at,q.declined_at,COALESCE(b.company_name,''),COALESCE(b.logo_sha256,'') FROM public.quote_public_links l JOIN public.quotes q ON q.quote_id=l.quote_id AND q.tenant_id=l.tenant_id LEFT JOIN public.tenant_company_branding b ON b.tenant_id=l.tenant_id WHERE l.token_hash=@hash";
        await using var command=new NpgsqlCommand(sql,connection);command.Parameters.AddWithValue("hash",hash);await using var reader=await command.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))return null;if(!reader.IsDBNull(5)||reader.GetFieldValue<DateTimeOffset>(4)<=DateTimeOffset.UtcNow)return null;var access=new QuotePublicAccess(reader.GetGuid(0),reader.GetGuid(1),reader.GetGuid(2),reader.GetInt32(3),reader.GetString(6),reader.GetString(7),reader.GetString(8),reader.GetString(9),reader.GetString(10),reader.GetDecimal(11),reader.GetDecimal(12),reader.GetDecimal(13),reader.GetDateTime(14),reader.IsDBNull(15)?null:reader.GetFieldValue<DateTimeOffset>(15),reader.IsDBNull(16)?null:reader.GetFieldValue<DateTimeOffset>(16),reader.GetString(17),reader.GetString(18));await reader.DisposeAsync();if(recordView){await using var view=new NpgsqlCommand("UPDATE public.quote_public_links SET first_viewed_at=COALESCE(first_viewed_at,NOW()),last_viewed_at=NOW(),visit_count=visit_count+1 WHERE link_id=@id",connection);view.Parameters.AddWithValue("id",access.LinkId);await view.ExecuteNonQueryAsync(ct);if(access.Status is "Ready" or "Sent"){await using var status=new NpgsqlCommand("UPDATE public.quotes SET status='Viewed',updated_at=NOW() WHERE quote_id=@quote AND version=@version AND status IN ('Ready','Sent')",connection);status.Parameters.AddWithValue("quote",access.QuoteId);status.Parameters.AddWithValue("version",access.Version);await status.ExecuteNonQueryAsync(ct);}}return access;
    }

    public static async Task<bool> DecideAsync(NpgsqlConnection connection,QuotePublicAccess access,string decision,string ipHash,CancellationToken ct=default)
    {
        if(decision is not("Accepted" or "Declined"))return false;await using var tx=await connection.BeginTransactionAsync(ct);await using(var insert=new NpgsqlCommand("INSERT INTO public.quote_decisions(decision_id,tenant_id,quote_id,quote_version,decision,ip_hash) VALUES(@id,@tenant,@quote,@version,@decision,@ip) ON CONFLICT(quote_id,quote_version) DO NOTHING",connection,tx)){insert.Parameters.AddWithValue("id",Guid.NewGuid());insert.Parameters.AddWithValue("tenant",access.TenantId);insert.Parameters.AddWithValue("quote",access.QuoteId);insert.Parameters.AddWithValue("version",access.Version);insert.Parameters.AddWithValue("decision",decision);insert.Parameters.AddWithValue("ip",ipHash??"");if(await insert.ExecuteNonQueryAsync(ct)==0){await tx.RollbackAsync(ct);return false;}}
        await using(var update=new NpgsqlCommand($"UPDATE public.quotes SET status=@decision,{(decision=="Accepted"?"accepted_at":"declined_at")}=NOW(),updated_at=NOW() WHERE quote_id=@quote AND tenant_id=@tenant AND version=@version AND status IN ('Ready','Sent','Viewed')",connection,tx)){update.Parameters.AddWithValue("decision",decision);update.Parameters.AddWithValue("quote",access.QuoteId);update.Parameters.AddWithValue("tenant",access.TenantId);update.Parameters.AddWithValue("version",access.Version);if(await update.ExecuteNonQueryAsync(ct)==0){await tx.RollbackAsync(ct);return false;}}await tx.CommitAsync(ct);return true;
    }

    public static async Task<bool> MarkSentAsync(NpgsqlConnection connection,QuoteDeliveryRequest request,CancellationToken ct=default)
    {
        if(!request.Confirmed||!request.Accepted)throw new InvalidOperationException("Only an explicitly confirmed SMTP delivery can mark a quote Sent.");
        await EnsureAsync(connection,ct);await using var command=new NpgsqlCommand("UPDATE public.quotes SET status='Sent',updated_at=NOW() WHERE tenant_id=@tenant AND quote_id=@quote AND version=@version AND status='Ready'",connection);command.Parameters.AddWithValue("tenant",request.TenantId);command.Parameters.AddWithValue("quote",request.QuoteId);command.Parameters.AddWithValue("version",request.Version);return await command.ExecuteNonQueryAsync(ct)==1;
    }

    public static string RenderPublic(QuotePublicAccess value,string token)
    {
        var lines=JsonSerializer.Deserialize<List<QuoteStoredLine>>(value.LinesJson,JsonOptions)??[];var decided=value.AcceptedAt.HasValue?"Quote accepted":value.DeclinedAt.HasValue?"Quote declined":"Review your quote";var buttons=value.AcceptedAt.HasValue||value.DeclinedAt.HasValue?"":$"<form method='post' action='/quote/{WebUtility.UrlEncode(token)}/decision'><button name='decision' value='Accepted'>Accept quote</button><button class='secondary' name='decision' value='Declined'>Decline quote</button></form>";var logo=string.IsNullOrWhiteSpace(value.LogoHash)?"":$"<img src='/branding/{value.TenantId:D}/logo/{WebUtility.HtmlEncode(value.LogoHash)}' alt='{H(value.CompanyName)}'>";var renderedLines=string.Join("",lines.Select(x=>$"<div class='line'><span>{H(x.Description)}<br><small>{H(x.Evidence)}</small></span><strong>{x.Amount:C}</strong></div>"));return $$$"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{{H(value.QuoteNumber)}}} · Quote details</title><style>body{margin:0;background:#f3f6f8;color:#17212b;font:16px Arial,sans-serif}main{max-width:720px;margin:30px auto;background:white;padding:38px;border-top:5px solid #0b5f86;box-shadow:0 8px 28px #1232}img{max-width:210px;max-height:80px}h1{color:#073f5b}.line{display:flex;justify-content:space-between;gap:20px;padding:13px 0;border-bottom:1px solid #dfe5e9}.totals{margin-top:20px;text-align:right}button{border:0;border-radius:4px;padding:13px 22px;background:#0b5f86;color:#fff;font-weight:bold;margin:18px 10px 0 0}button.secondary{background:#64717d}small{color:#64717d}@media(max-width:620px){main{margin:0;padding:24px}}</style></head><body><main>{{{logo}}}<p><small>{{{H(value.CompanyName)}}}</small></p><h1>{{{H(decided)}}}</h1><p>Hello {{{H(value.ClientName)}}}. Here are the approved details for your inspection quote.</p><p><strong>{{{H(value.Address)}}}</strong></p>{{{renderedLines}}}<div class='totals'><p>GST included: {{{value.Gst:C}}}</p><h2>Total: {{{value.Total:C}}}</h2><p>Valid until {{{value.ValidUntil:dd MMMM yyyy}}}</p></div><p>Acceptance confirms the quoted price and scope only. It does not book an appointment, sign Terms or confirm payment.</p>{{{buttons}}}</main></body></html>""";
    }

    private static async Task EnsureSettingsAsync(NpgsqlConnection connection,Guid tenantId,CancellationToken ct){await using var command=new NpgsqlCommand("INSERT INTO public.tenant_quote_settings(tenant_id) VALUES(@tenant) ON CONFLICT DO NOTHING",connection);command.Parameters.AddWithValue("tenant",tenantId);await command.ExecuteNonQueryAsync(ct);}
    private static object Row(NpgsqlDataReader r,bool detail)=>new{quoteId=r.GetGuid(0),quoteNumber=r.GetString(1),status=EffectiveStatus(r.GetString(2),r.GetDateTime(18)),version=r.GetInt32(3),catalogueVersion=r.GetInt32(4),canonicalAddress=r.GetString(5),placeId=r.GetString(6),latitude=r.IsDBNull(7)?null:(double?)r.GetDouble(7),longitude=r.IsDBNull(8)?null:(double?)r.GetDouble(8),clientName=r.GetString(9),clientEmail=r.GetString(10),property=JsonSerializer.Deserialize<object>(r.GetString(11)),imagery=JsonSerializer.Deserialize<object>(r.GetString(12)),suggestions=JsonSerializer.Deserialize<object>(r.GetString(13)),lines=JsonSerializer.Deserialize<object>(r.GetString(14)),subtotal=r.GetDecimal(15),gst=r.GetDecimal(16),total=r.GetDecimal(17),validUntil=r.GetDateTime(18).ToString("yyyy-MM-dd"),createdAt=r.GetDateTime(19),updatedAt=r.GetDateTime(20),acceptedAt=r.IsDBNull(21)?null:(DateTime?)r.GetDateTime(21),declinedAt=r.IsDBNull(22)?null:(DateTime?)r.GetDateTime(22),conversionPreview=new{enabled=false,status="pilot_required",message="THREED conversion remains disabled until a disposable write/read-back pilot passes.",jobState="Unscheduled",inspector="Unassigned",providerActions=false}};
    private static string EffectiveStatus(string status,DateTime valid)=>valid.Date<DateTime.UtcNow.Date&&status is "Ready" or "Sent" or "Viewed"?"Expired":status;
    private static decimal? ReadFloorArea(object? value){if(value is null)return null;try{var element=value is JsonElement json?json:JsonSerializer.SerializeToElement(value,JsonOptions);if(element.ValueKind!=JsonValueKind.Object)return null;foreach(var name in new[]{"floorArea","FloorArea","floor_area","totalArea","TotalArea","propertyFloorArea"})if(element.TryGetProperty(name,out var item)){if(item.ValueKind==JsonValueKind.Number&&item.TryGetDecimal(out var number)&&number>0)return number;if(decimal.TryParse(item.ToString(),NumberStyles.Number,CultureInfo.InvariantCulture,out number)&&number>0)return number;}}catch{}return null;}
    private static decimal Money(decimal v)=>Math.Round(v,2,MidpointRounding.AwayFromZero);private static string H(string? v)=>WebUtility.HtmlEncode(v??"");
}

public sealed record QuoteDraftSaveRequest(Guid TenantId,Guid? QuoteId,int ExpectedVersion,string IdempotencyKey,bool Confirmed,QuoteDraftPayload Draft);
public sealed record QuoteAddressEnrichmentRequest(Guid TenantId,string CanonicalAddress,string? PlaceId,double? Latitude,double? Longitude);
public sealed record QuoteDraftPayload(string CanonicalAddress,string? PlaceId,double? Latitude,double? Longitude,string? ClientName,string? ClientEmail,bool Ready,DateTime? ValidUntil,List<QuoteLineSelection> Lines,object? Property,object? Imagery,List<object>? Suggestions);
public sealed record QuoteLineSelection(string CatalogueItemId,decimal Quantity,bool IsBaseItem,bool Confirmed,string? Evidence);
public sealed record QuoteStoredLine(string CatalogueItemId,string Name,string Description,decimal Quantity,decimal UnitPrice,decimal Amount,bool IsBaseItem,string Evidence,string InvoiceItemId="");
public sealed record QuoteSaveResult(Guid QuoteId,string QuoteNumber,string Status,int Version,int CatalogueVersion,decimal Subtotal,decimal Gst,decimal Total,string ValidUntil,string? PublicToken,bool Replayed);
public sealed record QuoteDeliveryRequest(Guid TenantId,Guid QuoteId,int Version,bool Accepted,bool Confirmed);
public sealed record QuotePublicAccess(Guid LinkId,Guid TenantId,Guid QuoteId,int Version,string QuoteNumber,string Status,string Address,string ClientName,string LinesJson,decimal Subtotal,decimal Gst,decimal Total,DateTime ValidUntil,DateTimeOffset? AcceptedAt,DateTimeOffset? DeclinedAt,string CompanyName,string LogoHash);
public sealed class QuoteVersionConflictException:Exception{public QuoteVersionConflictException():base("The quote changed. Reload it before saving again."){}}
